spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pesa_api_db
    username: postgres
    password: ${DB_PASSWORD:postgres}

logging:
  level:
    com.margaretnjoki.expensetracker: DEBUG
    org.hibernate.SQL: DEBUG


mpesa:
  consumer-key: ${MPESA_CONSUMER_KEY}
  consumer-secret: ${MPESA_CONSUMER_SECRET}
  shortcode: ${MPESA_SHORTCODE:174379}
  passkey: ${MPESA_PASSKEY}
  callback-url: ${MPESA_CALLBACK_URL}
  base-url: https://sandbox.safaricom.co.ke